version: "3"

services:

  wololo:
    build: .
    image: wololo:latest

    container_name: wololo
    restart: unless-stopped

    environment:
      WOLOLOIP: "0.0.0.0"
      WOLOLOPORT: "8089"
      WOLOLOBCASTIP: "192.168.1.255:9"

    volumes:
      - ./config.json:/wololo/config.json
      - ./devices.json:/wololo/devices.json
      - ./static:/wololo/static
      - ./templates:/wololo/templates

    network_mode: host